[package]
name = "rust-ai-ui-server"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.0-rc.2"
async-graphql = "5.0.6"
async-graphql-rocket = "5.0.6"
futures-core = "0.3.27"
tokio = "1.26.0"
tokio-stream = "0.1.12"
